spring.application.name=TATTOO_SHOP

# Server
server.port=${PORT:8080}

# MySQL Database (Using values from your image)
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=QYYkTKoEIKCxtluXpVIgAsNEoMArLfDW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rameshbalu21@gmail.com
spring.mail.password=mlucwzaqqopfivyo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true